#!/usr/bin/env node

var data = ''
process.stdin.setEncoding('utf8')

process.stdin.on('readable', function() {
  var chunk = process.stdin.read()
  if (chunk !== null) {
    data += chunk
  }
})

process.stdin.on('end', function() {
  process.stdout.write(
    '> ' + data.replace(/\n/g, '\n> ')
  );
});

