#!/usr/bin/env node

const cp = require('child_process')
const util = require('util')
const spawn = util.promisify(cp.spawn)
const exec = util.promisify(cp.exec)

// displayplacer: https://github.com/jakehilborn/displayplacer

const DISPLAY_ID = '71AFE85C-248E-7D79-BF75-B3539979FCD3'

async function main() {
  const commands = [
    `displayplacer "id:0A3A2A4F-BFD9-A636-6362-142C157B04AB res:2560x1440 color_depth:8 scaling:on origin:(0,0) degree:0" "id:71AFE85C-248E-7D79-BF75-B3539979FCD3 res:1280x720 color_depth:8 scaling:on origin:(2560,0) degree:0"`,
    `open /Applications/ScreenFlow.app`,
  ]
  console.log(`Getting ready to start recording!`)
  await Promise.all(
    commands.map(cmd => spawn(cmd, {stdio: 'inherit', shell: true})),
  )
}

main()
